create table car (id  bigserial not null, car_made varchar(255), licence_plate varchar(255), vin_code varchar(255) not null, primary key (id));
create table customer (id  bigserial not null, email varchar(255), first_name varchar(255) not null, last_name varchar(255), tel_number varchar(255), primary key (id));
create table oblik_user (id  bigserial not null, deleted boolean not null, name varchar(255) not null, password varchar(255) not null, role int4, primary key (id));
create table part (id  bigserial not null, description TEXT, name varchar(255) not null, purchase_price float8, retail_price float8 not null, primary key (id));
create table part_count (id  bigserial not null, amount int4 not null, part_name varchar(255), retail_price float8, part_id int8, repair_order_id int8 not null, primary key (id));
create table record (id  bigserial not null, action varchar(255), car_id int8, oblik_user_id int8 not null, repair_order_id int8, work_id int8, primary key (id));
create table repair_order (id  bigserial not null, amount_payed_in_advance float8, order_closed TIMESTAMP, order_opened TIMESTAMP not null, payed_for boolean not null, problem TEXT not null, car_id int8, customer_id int8 not null, primary key (id));
create table work (id  bigserial not null, price float8, work_done boolean not null, work_name varchar(255), oblik_user_id int8, work_type_id int8, repair_order_id int8, primary key (id));
create table work_type (id  bigserial not null, description TEXT, name varchar(255) not null, price float8 not null, primary key (id));
alter table part_count add constraint FKs643pwogcoalnd6j9x9r3au2f foreign key (part_id) references part;
alter table part_count add constraint FKoi98sv44fjrcgoyc11sbsguuj foreign key (repair_order_id) references repair_order;
alter table record add constraint FKilljek5soyj16m5ykklmvkq5c foreign key (car_id) references car;
alter table record add constraint FKdhy7u1ox15heag15cf4290yd2 foreign key (oblik_user_id) references oblik_user;
alter table record add constraint FKohfs7p1f88yxfp3fakqww86gq foreign key (repair_order_id) references repair_order;
alter table record add constraint FKq8t9wfwogkjvpt5oiv8fn8gkq foreign key (work_id) references work;
alter table repair_order add constraint FK3mnrgyxw45inwyt1193yncsqo foreign key (car_id) references car;
alter table repair_order add constraint FK2mfmcsusecb0lid22t3h9wiqy foreign key (customer_id) references customer;
alter table work add constraint FKgsscrm5nn1wyvukrgl0cx3ol7 foreign key (oblik_user_id) references oblik_user;
alter table work add constraint FKptehhxv81md59wi7d6ac4ioox foreign key (work_type_id) references work_type;
alter table work add constraint FKqaj1mr3hlq0vjoqulau77uy5v foreign key (repair_order_id) references repair_order;